environment: D
grpc_address: 10000
http_address: 9003

mysql:
  address: 127.0.0.1
  database: users
  username: root
  password: rootroot
  protocol: tcp
  parse_time: true
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0


