# config.yaml

http:
  host: 127.0.0.1
  port: 9002

db:
  dialect: mysql
  address: 127.0.0.1
  database: shipping
  username: root
  password: rootroot
  protocol: tcp
  parse_time: true

redis:
  address: 127.0.0.1
  port: 6379
  password: nil
  db: 0

currency_grpc:
  address: 127.0.0.1
  port: 9092
