// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: protos/currency.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Currencies is an enum which represents the allowed currencies for the API
// List sourced from the Fed: https://www.federalreserve.gov/releases/h10/current/
type Currencies int32

const (
	Currencies_USD Currencies = 0  // US Dollar
	Currencies_AUD Currencies = 1  // Australian Dollar
	Currencies_BRL Currencies = 2  // Brazilian Real
	Currencies_CAD Currencies = 3  // Canadian Dollar
	Currencies_CNY Currencies = 4  // Chinese Yuan (Renminbi)
	Currencies_DKK Currencies = 5  // Danish Krone
	Currencies_EUR Currencies = 6  // (EMU) Euro
	Currencies_HKD Currencies = 7  // Hong Kong Dollar
	Currencies_INR Currencies = 8  // Indian Rupee
	Currencies_JPY Currencies = 9  // Japanese Yen
	Currencies_MYR Currencies = 10 // Malaysian Ringgit
	Currencies_MXN Currencies = 11 // Mexican Peso
	Currencies_NZD Currencies = 12 // New Zealand Dollar
	Currencies_NOK Currencies = 13 // Norwegian Krone
	Currencies_SGD Currencies = 14 // Singapore Dollar
	Currencies_ZAR Currencies = 15 // South African Rand
	Currencies_KRW Currencies = 16 // (South) Korean Won
	Currencies_LKR Currencies = 17 // Sri Lanka Rupee
	Currencies_SEK Currencies = 18 // Swedish Krona
	Currencies_CHF Currencies = 19 // Swiss Franc
	Currencies_TWD Currencies = 20 // New Taiwan Dollar
	Currencies_THB Currencies = 21 // Taiwanese Baht
	Currencies_GBP Currencies = 22 // (GB) Pound Sterling
	Currencies_VES Currencies = 23 // Bolivar Soberano
)

// Enum value maps for Currencies.
var (
	Currencies_name = map[int32]string{
		0:  "USD",
		1:  "AUD",
		2:  "BRL",
		3:  "CAD",
		4:  "CNY",
		5:  "DKK",
		6:  "EUR",
		7:  "HKD",
		8:  "INR",
		9:  "JPY",
		10: "MYR",
		11: "MXN",
		12: "NZD",
		13: "NOK",
		14: "SGD",
		15: "ZAR",
		16: "KRW",
		17: "LKR",
		18: "SEK",
		19: "CHF",
		20: "TWD",
		21: "THB",
		22: "GBP",
		23: "VES",
	}
	Currencies_value = map[string]int32{
		"USD": 0,
		"AUD": 1,
		"BRL": 2,
		"CAD": 3,
		"CNY": 4,
		"DKK": 5,
		"EUR": 6,
		"HKD": 7,
		"INR": 8,
		"JPY": 9,
		"MYR": 10,
		"MXN": 11,
		"NZD": 12,
		"NOK": 13,
		"SGD": 14,
		"ZAR": 15,
		"KRW": 16,
		"LKR": 17,
		"SEK": 18,
		"CHF": 19,
		"TWD": 20,
		"THB": 21,
		"GBP": 22,
		"VES": 23,
	}
)

func (x Currencies) Enum() *Currencies {
	p := new(Currencies)
	*p = x
	return p
}

func (x Currencies) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currencies) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_currency_proto_enumTypes[0].Descriptor()
}

func (Currencies) Type() protoreflect.EnumType {
	return &file_protos_currency_proto_enumTypes[0]
}

func (x Currencies) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currencies.Descriptor instead.
func (Currencies) EnumDescriptor() ([]byte, []int) {
	return file_protos_currency_proto_rawDescGZIP(), []int{0}
}

// RateRequest defines the request for a GetRate call
type RateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Base is the base currency code for the rate
	Base Currencies `protobuf:"varint,1,opt,name=Base,proto3,enum=Currencies" json:"Base,omitempty"`
	// Destination is the destination currency code for the rate
	Destination Currencies `protobuf:"varint,2,opt,name=Destination,proto3,enum=Currencies" json:"Destination,omitempty"`
}

func (x *RateRequest) Reset() {
	*x = RateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_currency_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRequest) ProtoMessage() {}

func (x *RateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_currency_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRequest.ProtoReflect.Descriptor instead.
func (*RateRequest) Descriptor() ([]byte, []int) {
	return file_protos_currency_proto_rawDescGZIP(), []int{0}
}

func (x *RateRequest) GetBase() Currencies {
	if x != nil {
		return x.Base
	}
	return Currencies_USD
}

func (x *RateRequest) GetDestination() Currencies {
	if x != nil {
		return x.Destination
	}
	return Currencies_USD
}

// RateResponse is the response from a GetRate call, it contains
// rate which is a floating point number and can be used to convert between the
// two currencies specified in the request.
type RateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate float32 `protobuf:"fixed32,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_currency_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_currency_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_protos_currency_proto_rawDescGZIP(), []int{1}
}

func (x *RateResponse) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_protos_currency_proto protoreflect.FileDescriptor

var file_protos_currency_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x0b, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65,
	0x73, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x2a, 0xe4, 0x01, 0x0a, 0x0a, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53, 0x44,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x55, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42,
	0x52, 0x4c, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x41, 0x44, 0x10, 0x03, 0x12, 0x07, 0x0a,
	0x03, 0x43, 0x4e, 0x59, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x4b, 0x4b, 0x10, 0x05, 0x12,
	0x07, 0x0a, 0x03, 0x45, 0x55, 0x52, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x4b, 0x44, 0x10,
	0x07, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x52, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x50,
	0x59, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x59, 0x52, 0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03,
	0x4d, 0x58, 0x4e, 0x10, 0x0b, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x5a, 0x44, 0x10, 0x0c, 0x12, 0x07,
	0x0a, 0x03, 0x4e, 0x4f, 0x4b, 0x10, 0x0d, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x47, 0x44, 0x10, 0x0e,
	0x12, 0x07, 0x0a, 0x03, 0x5a, 0x41, 0x52, 0x10, 0x0f, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x52, 0x57,
	0x10, 0x10, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4b, 0x52, 0x10, 0x11, 0x12, 0x07, 0x0a, 0x03, 0x53,
	0x45, 0x4b, 0x10, 0x12, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x48, 0x46, 0x10, 0x13, 0x12, 0x07, 0x0a,
	0x03, 0x54, 0x57, 0x44, 0x10, 0x14, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x48, 0x42, 0x10, 0x15, 0x12,
	0x07, 0x0a, 0x03, 0x47, 0x42, 0x50, 0x10, 0x16, 0x12, 0x07, 0x0a, 0x03, 0x56, 0x45, 0x53, 0x10,
	0x17, 0x32, 0x32, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x26, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_currency_proto_rawDescOnce sync.Once
	file_protos_currency_proto_rawDescData = file_protos_currency_proto_rawDesc
)

func file_protos_currency_proto_rawDescGZIP() []byte {
	file_protos_currency_proto_rawDescOnce.Do(func() {
		file_protos_currency_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_currency_proto_rawDescData)
	})
	return file_protos_currency_proto_rawDescData
}

var file_protos_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_currency_proto_goTypes = []interface{}{
	(Currencies)(0),      // 0: Currencies
	(*RateRequest)(nil),  // 1: RateRequest
	(*RateResponse)(nil), // 2: RateResponse
}
var file_protos_currency_proto_depIdxs = []int32{
	0, // 0: RateRequest.Base:type_name -> Currencies
	0, // 1: RateRequest.Destination:type_name -> Currencies
	1, // 2: Currency.GetRate:input_type -> RateRequest
	2, // 3: Currency.GetRate:output_type -> RateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_currency_proto_init() }
func file_protos_currency_proto_init() {
	if File_protos_currency_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_currency_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_currency_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_currency_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_currency_proto_goTypes,
		DependencyIndexes: file_protos_currency_proto_depIdxs,
		EnumInfos:         file_protos_currency_proto_enumTypes,
		MessageInfos:      file_protos_currency_proto_msgTypes,
	}.Build()
	File_protos_currency_proto = out.File
	file_protos_currency_proto_rawDesc = nil
	file_protos_currency_proto_goTypes = nil
	file_protos_currency_proto_depIdxs = nil
}
