# config.yaml

http:
  host: 127.0.0.1
  port: 9001

db:
  dialect: mysql
  address: 127.0.0.1
  port: 3306
  database: products
  username: root
  password: rootroot
  protocol: tcp
  parse_time: true

redis:
  address: 127.0.0.1
  port: 6379
  password: ""
  db: 1

product_grpc:
  address: 127.0.0.1
  port: 9093

currency_grpc:
  address: 127.0.0.1
  port: 9092
